// <auto-generated />
using System;
using AspNetCoreCrudDemo.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AspNetCoreCrudDemo.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260402231020_AddCoursesTable")]
    partial class AddCoursesTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AspNetCoreCrudDemo.Models.Course", b =>
                {
                    b.Property<int>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CourseId"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CourseId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            CourseId = 1,
                            Category = "Yazılım",
                            Description = "Modern web uygulamaları ve güçlü API'ler geliştirmek için C# ve .NET Core ekosistemini sıfırdan zirveye öğrenin. Katmanlı mimari, Entity Framework ve Onion Architecture prensiplerine hakim olun.",
                            Duration = "120 Saat",
                            ImageUrl = "/images/csharp_backend.png",
                            Rating = 4.9000000000000004,
                            Title = "C# ile .NET Core (Backend)"
                        },
                        new
                        {
                            CourseId = 2,
                            Category = "Web",
                            Description = "Günümüzün en popüler JavaScript kütüphaneleriyle uçtan uca modern ve dinamik web platformları inşa edin. MERN stack ile gerçek projeler üzerinden Full Stack yetkinliği kazanın.",
                            Duration = "95 Saat",
                            ImageUrl = "/images/react_nodejs.png",
                            Rating = 4.7999999999999998,
                            Title = "React & Node.js (Full Stack)"
                        },
                        new
                        {
                            CourseId = 3,
                            Category = "Yapay Zeka",
                            Description = "Büyük veriyi analiz edin, yapay zeka modelleri kurun ve geleceğin mesleği olan veri biliminde uzmanlaşın. Pandas, NumPy ve Scikit-learn kütüphanelerini ustalıkla kullanın.",
                            Duration = "80 Saat",
                            ImageUrl = "/images/python_data.png",
                            Rating = 4.9000000000000004,
                            Title = "Python ile Veri Bilimi (Data Science)"
                        },
                        new
                        {
                            CourseId = 4,
                            Category = "Kurumsal",
                            Description = "Büyük şirketlerin ve bankaların vazgeçilmez altyapısı olan Java Spring Boot ile kurumsal mimariye adım atın. Microservices ve Cloud-Native geliştirme temellerini öğrenin.",
                            Duration = "110 Saat",
                            ImageUrl = "/images/java_spring.png",
                            Rating = 4.7000000000000002,
                            Title = "Java Spring Boot (Kurumsal Web)"
                        },
                        new
                        {
                            CourseId = 5,
                            Category = "Mobil",
                            Description = "Tek bir kod tabanından hem iOS hem de Android için native performansında muhteşem mobil uygulamalar geliştirin. Cross-platform dünyasında aranan bir geliştirici olun.",
                            Duration = "85 Saat",
                            ImageUrl = "/images/flutter_dart.png",
                            Rating = 4.9000000000000004,
                            Title = "Flutter & Dart (Mobil Uygulama)"
                        });
                });

            modelBuilder.Entity("AspNetCoreCrudDemo.Models.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentId"));

                    b.Property<string>("Course")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EnrollmentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhotoPath")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StudentId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("AspNetCoreCrudDemo.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefreshTokenExpiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
